### ISSUE TITLE
cameras tracking

### ISSUE THREAD

**Issue by HyppoNymous** [JulesThuillier/VRTracker#1]
How many cameras do we need to track a headset in full 360 ?
Can software work with more than two cameras and calibrate automatically ? 
Could this be used to track controllers like the Vive Headset ?

**Comment by JulesThuillier** [comment]
Hi !
_How many cameras do we need to track a headset in full 360 ?_
As long as the Tag on the headset is seen by at least two cameras, you are being tracked. 

_Can software work with more than two cameras and calibrate automatically ?_ 
Yes we are currently working on that, it is not released yet but it will be a simple software update

_Could this be used to track controllers like the Vive Headset ?_
That's our goal ! We are not looking at competing with Vive precision though, but more to have an Open Source system compatible across multiple devices. The new Tag we are working on will also include a 9DOF IMU and external pinouts so you can transform it in a controller using Arduino sketch :)
